version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - debezium-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - debezium-network

  connect-init:
    image: alpine:latest
    depends_on:
      - kafka
    volumes:
      - /path/to/debezium/plugins:/kafka/connect/jars
    entrypoint: >
      sh -c "apk add --no-cache curl tar &&
      curl -L -o /kafka/connect/jars/debezium-connector-postgres-plugin.tar.gz https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.8.0.Final/debezium-connector-postgres-1.8.0.Final-plugin.tar.gz &&
      tar -xzf /kafka/connect/jars/debezium-connector-postgres-plugin.tar.gz -C /kafka/connect/jars &&
      curl -L -o /kafka/connect/jars/confluentinc-kafka-connect-jdbc-10.2.0.tar.gz https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/10.2.0/kafka-connect-jdbc-10.2.0.tar.gz &&
      tar -xzf /kafka/connect/jars/confluentinc-kafka-connect-jdbc-10.2.0.tar.gz -C /kafka/connect/jars &&
      rm /kafka/connect/jars/debezium-connector-postgres-plugin.tar.gz /kafka/connect/jars/confluentinc-kafka-connect-jdbc-10.2.0.tar.gz"

  connect:
    image: debezium/connect:latest
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_PLUGIN_PATH=/kafka/connect/jars
    depends_on:
      - kafka
      - connect-init
    volumes:
      - /path/to/debezium/plugins:/kafka/connect/jars
    networks:
      - debezium-network

  connector-setup:
    image: curlimages/curl:latest
    depends_on:
      - connect
    networks:
      - debezium-network
    volumes:
      - ./connectors:/connectors
    entrypoint: >
      sh -c "sleep 10 &&
      curl -X POST -H 'Content-Type: application/json' --data @/connectors/postgres-connector.json http://connect:8083/connectors &&
      curl -X POST -H 'Content-Type: application/json' --data @/connectors/jdbc-sink-connector.json http://connect:8083/connectors"

networks:
  debezium-network:
    driver: bridge
