version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: debezium/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  postgres_source:
    image: debezium/postgres:latest
    environment:
      - POSTGRES_DB=ques_db
      - POSTGRES_USER=bks
      - POSTGRES_PASSWORD=passowrd
    ports:
      - "5432:5432"
    depends_on:
      - zookeeper
      - kafka

  postgres_target:
    image: debezium/postgres:latest
    environment:
      - POSTGRES_DB=quiz_db
      - POSTGRES_USER=bks
      - POSTGRES_PASSWORD=passowrd
    ports:
      - "5433:5432"
    depends_on:
      - zookeeper
      - kafka

  connect:
    image: debezium/connect:latest
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
    volumes:
      - /path/to/debezium/plugins:/kafka/connect/jars
